-------------- Problem 1

{-If we list all the natural numbers below 10 that are multiples of 3 or 5, we
get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the
multiples of 3 or 5 below 1000-}

prob1 = sum [x  | x <- [1..999], x `mod` 3 == 0 || x `mod` 5 == 0]


-------------- Problem 2

{-Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.-}

fibs = 1 : 2 : zipWith (+) fibs (tail fibs)
prob2 = sum [x | x <- takeWhile (<= 4000000) fibs, even x]


-------------- Problem 3

{-The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?-}

factors_of:: Int -> [Int]
factors_of n = filter (\i -> n `mod` i == 0) [1..(ceiling (sqrt (fromIntegral n)))] ++ [n]
isPrime n = length (factors_of n) == 2
prob3 = last $ filter isPrime $ factors_of 600851475143


-------------- Problem 4

{-A palindromic number reads the same both ways. The largest palindrome made
from the product of two 2-digit numbers is 9009 = 91 99. Find the largest
palindrome made from the product of two 3-digit numbers.-}

isPalindrome n = (show n) == (reverse $ show n)
prob4 = maximum [x*y | x<-[100..999], y<-[x..999], isPalindrome $ x*y]


-------------- Problem 5

{-2520 is the smallest number that can be divided by each of the numbers from 1
to 10 without any remainder. What is the smallest positive number that is
evenly divisible by all of the numbers from 1 to 20?-}

prob5 = foldl1 lcm [1..20]


-------------- Problem 6

{-The sum of the squares of the first ten natural numbers is, 12 + 22 + ... +
102 = 385 The square of the sum of the first ten natural numbers is, (1 + 2 +
... + 10)2 = 552 = 3025 Hence the difference between the sum of the squares of
the first ten natural numbers and the square of the sum is 3025 385 = 2640.
Find the difference between the sum of the squares of the first one hundred
natural numbers and the square of the sum.-}

prob6 = ((sum [1..100]) ^2) - (sum $ map (^2) [1..100])


-------------- Problem 7

{-By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see
that the 6th prime is 13. What is the 10 001st prime number?-}

primes = [x | x <-[2..], isPrime x]
prob7 = primes !! 9999


-------------- Problem 8

