"""
Project Euler Problem 2

Problem text:

    Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms
    will be:

    [1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...]

    By considering the terms in the Fibonacci sequence whose values do
    not exceed four million, find the sum of the even-valued terms.

Date: Wed Dec 18 14:38:25 MST 2013

"""
import Tools.fiblt
euler2() = sum(fiblt(4e6)[mod(x, 2) .== 0])
